var annotated_dup =
[
    [ "nk", null, [
      [ "audio", null, [
        [ "AudioData", "structnk_1_1audio_1_1_audio_data.html", "structnk_1_1audio_1_1_audio_data" ],
        [ "AudioInfo", "structnk_1_1audio_1_1_audio_info.html", "structnk_1_1audio_1_1_audio_info" ]
      ] ],
      [ "builtin", null, [
        [ "detail", null, [
          [ "ScanfOut", "structnk_1_1builtin_1_1detail_1_1_scanf_out.html", null ]
        ] ],
        [ "CartPair", "structnk_1_1builtin_1_1_cart_pair.html", "structnk_1_1builtin_1_1_cart_pair" ],
        [ "CartTriple", "structnk_1_1builtin_1_1_cart_triple.html", "structnk_1_1builtin_1_1_cart_triple" ],
        [ "CylTriple", "structnk_1_1builtin_1_1_cyl_triple.html", "structnk_1_1builtin_1_1_cyl_triple" ],
        [ "EllipJ", "structnk_1_1builtin_1_1_ellip_j.html", "structnk_1_1builtin_1_1_ellip_j" ],
        [ "EllipKE", "structnk_1_1builtin_1_1_ellip_k_e.html", "structnk_1_1builtin_1_1_ellip_k_e" ],
        [ "FindgroupsResult", "structnk_1_1builtin_1_1_findgroups_result.html", "structnk_1_1builtin_1_1_findgroups_result" ],
        [ "GroupcountsResult", "structnk_1_1builtin_1_1_groupcounts_result.html", "structnk_1_1builtin_1_1_groupcounts_result" ],
        [ "GroupsummaryResult", "structnk_1_1builtin_1_1_groupsummary_result.html", "structnk_1_1builtin_1_1_groupsummary_result" ],
        [ "HistBinSpec", "structnk_1_1builtin_1_1_hist_bin_spec.html", null ],
        [ "InpolygonResult", "structnk_1_1builtin_1_1_inpolygon_result.html", "structnk_1_1builtin_1_1_inpolygon_result" ],
        [ "MatchpairsResult", "structnk_1_1builtin_1_1_matchpairs_result.html", "structnk_1_1builtin_1_1_matchpairs_result" ],
        [ "PadeCoef", "structnk_1_1builtin_1_1_pade_coef.html", "structnk_1_1builtin_1_1_pade_coef" ],
        [ "PolarPair", "structnk_1_1builtin_1_1_polar_pair.html", "structnk_1_1builtin_1_1_polar_pair" ],
        [ "PolyDiv", "structnk_1_1builtin_1_1_poly_div.html", "structnk_1_1builtin_1_1_poly_div" ],
        [ "PolyxpolyResult", "structnk_1_1builtin_1_1_polyxpoly_result.html", "structnk_1_1builtin_1_1_polyxpoly_result" ],
        [ "ResidueResult", "structnk_1_1builtin_1_1_residue_result.html", "structnk_1_1builtin_1_1_residue_result" ],
        [ "RngContext", "classnk_1_1builtin_1_1_rng_context.html", "classnk_1_1builtin_1_1_rng_context" ],
        [ "ShiftDimAuto", "structnk_1_1builtin_1_1_shift_dim_auto.html", "structnk_1_1builtin_1_1_shift_dim_auto" ],
        [ "SphTriple", "structnk_1_1builtin_1_1_sph_triple.html", "structnk_1_1builtin_1_1_sph_triple" ],
        [ "Surface3", "structnk_1_1builtin_1_1_surface3.html", "structnk_1_1builtin_1_1_surface3" ]
      ] ],
      [ "bundle", null, [
        [ "HelpCatalog", "classnk_1_1bundle_1_1_help_catalog.html", null ],
        [ "HelpCategory", "structnk_1_1bundle_1_1_help_category.html", null ],
        [ "HelpEntry", "structnk_1_1bundle_1_1_help_entry.html", null ],
        [ "HelpLibrary", "classnk_1_1bundle_1_1_help_library.html", null ],
        [ "HelpSection", "structnk_1_1bundle_1_1_help_section.html", null ]
      ] ],
      [ "comm", null, [
        [ "CyclgenResult", "structnk_1_1comm_1_1_cyclgen_result.html", "structnk_1_1comm_1_1_cyclgen_result" ],
        [ "DecodeResult", "structnk_1_1comm_1_1_decode_result.html", "structnk_1_1comm_1_1_decode_result" ],
        [ "DpcmOptResult", "structnk_1_1comm_1_1_dpcm_opt_result.html", "structnk_1_1comm_1_1_dpcm_opt_result" ],
        [ "EncodeResult", "structnk_1_1comm_1_1_encode_result.html", "structnk_1_1comm_1_1_encode_result" ],
        [ "HammgenResult", "structnk_1_1comm_1_1_hammgen_result.html", "structnk_1_1comm_1_1_hammgen_result" ],
        [ "QuantizResult", "structnk_1_1comm_1_1_quantiz_result.html", "structnk_1_1comm_1_1_quantiz_result" ]
      ] ],
      [ "control", null, [
        [ "BodeResult", "structnk_1_1control_1_1_bode_result.html", "structnk_1_1control_1_1_bode_result" ],
        [ "CovarResult", "structnk_1_1control_1_1_covar_result.html", "structnk_1_1control_1_1_covar_result" ],
        [ "DampResult", "structnk_1_1control_1_1_damp_result.html", "structnk_1_1control_1_1_damp_result" ],
        [ "MarginResult", "structnk_1_1control_1_1_margin_result.html", "structnk_1_1control_1_1_margin_result" ],
        [ "NyquistResult", "structnk_1_1control_1_1_nyquist_result.html", "structnk_1_1control_1_1_nyquist_result" ],
        [ "RiccatiResult", "structnk_1_1control_1_1_riccati_result.html", "structnk_1_1control_1_1_riccati_result" ],
        [ "StateSpace", "structnk_1_1control_1_1_state_space.html", null ],
        [ "Tf2ZpResult", "structnk_1_1control_1_1_tf2_zp_result.html", "structnk_1_1control_1_1_tf2_zp_result" ]
      ] ],
      [ "detail", null, [
        [ "ScratchStorage", "structnk_1_1detail_1_1_scratch_storage.html", null ],
        [ "ThreadPool", "classnk_1_1detail_1_1_thread_pool.html", null ],
        [ "value_type_for", "structnk_1_1detail_1_1value__type__for.html", null ],
        [ "value_type_for&lt; double &gt;", "structnk_1_1detail_1_1value__type__for_3_01double_01_4.html", null ],
        [ "value_type_for&lt; float &gt;", "structnk_1_1detail_1_1value__type__for_3_01float_01_4.html", null ],
        [ "value_type_for&lt; std::complex&lt; double &gt; &gt;", "structnk_1_1detail_1_1value__type__for_3_01std_1_1complex_3_01double_01_4_01_4.html", null ],
        [ "value_type_for&lt; std::int16_t &gt;", "structnk_1_1detail_1_1value__type__for_3_01std_1_1int16__t_01_4.html", null ],
        [ "value_type_for&lt; std::int32_t &gt;", "structnk_1_1detail_1_1value__type__for_3_01std_1_1int32__t_01_4.html", null ],
        [ "value_type_for&lt; std::int64_t &gt;", "structnk_1_1detail_1_1value__type__for_3_01std_1_1int64__t_01_4.html", null ],
        [ "value_type_for&lt; std::int8_t &gt;", "structnk_1_1detail_1_1value__type__for_3_01std_1_1int8__t_01_4.html", null ],
        [ "value_type_for&lt; std::uint16_t &gt;", "structnk_1_1detail_1_1value__type__for_3_01std_1_1uint16__t_01_4.html", null ],
        [ "value_type_for&lt; std::uint32_t &gt;", "structnk_1_1detail_1_1value__type__for_3_01std_1_1uint32__t_01_4.html", null ],
        [ "value_type_for&lt; std::uint64_t &gt;", "structnk_1_1detail_1_1value__type__for_3_01std_1_1uint64__t_01_4.html", null ],
        [ "value_type_for&lt; std::uint8_t &gt;", "structnk_1_1detail_1_1value__type__for_3_01std_1_1uint8__t_01_4.html", null ]
      ] ],
      [ "figrender", null, [
        [ "Rgb", "structnk_1_1figrender_1_1_rgb.html", null ],
        [ "StyleParts", "structnk_1_1figrender_1_1_style_parts.html", null ],
        [ "TextExtras", "structnk_1_1figrender_1_1_text_extras.html", null ],
        [ "NamedPaletteHex", "structnk_1_1figrender_1_1_named_palette_hex.html", null ],
        [ "Cmd", "structnk_1_1figrender_1_1_cmd.html", null ],
        [ "AxisRange", "structnk_1_1figrender_1_1_axis_range.html", null ],
        [ "Rect", "structnk_1_1figrender_1_1_rect.html", null ],
        [ "Raster", "classnk_1_1figrender_1_1_raster.html", null ]
      ] ],
      [ "image", null, [
        [ "AdaptHistEqOptions", "structnk_1_1image_1_1_adapt_hist_eq_options.html", "structnk_1_1image_1_1_adapt_hist_eq_options" ],
        [ "DeconvregResult", "structnk_1_1image_1_1_deconvreg_result.html", "structnk_1_1image_1_1_deconvreg_result" ]
      ] ],
      [ "io", null, [
        [ "FsContext", "classnk_1_1io_1_1_fs_context.html", "classnk_1_1io_1_1_fs_context" ]
      ] ],
      [ "linalg", null, [
        [ "BalanceResult", "structnk_1_1linalg_1_1_balance_result.html", "structnk_1_1linalg_1_1_balance_result" ],
        [ "NnlsResult", "structnk_1_1linalg_1_1_nnls_result.html", "structnk_1_1linalg_1_1_nnls_result" ]
      ] ],
      [ "ops", null, [
        [ "DimsArg", "structnk_1_1ops_1_1_dims_arg.html", null ],
        [ "NanSumCount", "structnk_1_1ops_1_1_nan_sum_count.html", null ],
        [ "RngContext", "classnk_1_1ops_1_1_rng_context.html", "classnk_1_1ops_1_1_rng_context" ],
        [ "SizeSpec", "structnk_1_1ops_1_1_size_spec.html", null ]
      ] ],
      [ "runtime", null, [
        [ "LastWarn", "structnk_1_1runtime_1_1_last_warn.html", "structnk_1_1runtime_1_1_last_warn" ]
      ] ],
      [ "signal", null, [
        [ "CusumResult", "structnk_1_1signal_1_1_cusum_result.html", "structnk_1_1signal_1_1_cusum_result" ],
        [ "Fir2Options", "structnk_1_1signal_1_1_fir2_options.html", "structnk_1_1signal_1_1_fir2_options" ]
      ] ],
      [ "stats", null, [
        [ "CanoncorrResult", "structnk_1_1stats_1_1_canoncorr_result.html", "structnk_1_1stats_1_1_canoncorr_result" ],
        [ "GlmfitResult", "structnk_1_1stats_1_1_glmfit_result.html", "structnk_1_1stats_1_1_glmfit_result" ],
        [ "Grp2idxResult", "structnk_1_1stats_1_1_grp2idx_result.html", "structnk_1_1stats_1_1_grp2idx_result" ],
        [ "LassoResult", "structnk_1_1stats_1_1_lasso_result.html", "structnk_1_1stats_1_1_lasso_result" ],
        [ "NlinfitResult", "structnk_1_1stats_1_1_nlinfit_result.html", "structnk_1_1stats_1_1_nlinfit_result" ],
        [ "NormalizeResult", "structnk_1_1stats_1_1_normalize_result.html", "structnk_1_1stats_1_1_normalize_result" ],
        [ "RobustcovResult", "structnk_1_1stats_1_1_robustcov_result.html", "structnk_1_1stats_1_1_robustcov_result" ],
        [ "RobustfitResult", "structnk_1_1stats_1_1_robustfit_result.html", "structnk_1_1stats_1_1_robustfit_result" ]
      ] ],
      [ "wavelet", null, [
        [ "DdencmpResult", "structnk_1_1wavelet_1_1_ddencmp_result.html", "structnk_1_1wavelet_1_1_ddencmp_result" ],
        [ "Dwt2Result", "structnk_1_1wavelet_1_1_dwt2_result.html", null ],
        [ "FilterBank", "structnk_1_1wavelet_1_1_filter_bank.html", null ],
        [ "HaartResult", "structnk_1_1wavelet_1_1_haart_result.html", "structnk_1_1wavelet_1_1_haart_result" ],
        [ "OrthfiltResult", "structnk_1_1wavelet_1_1_orthfilt_result.html", "structnk_1_1wavelet_1_1_orthfilt_result" ],
        [ "Wavedec2Result", "structnk_1_1wavelet_1_1_wavedec2_result.html", null ],
        [ "WenergyResult", "structnk_1_1wavelet_1_1_wenergy_result.html", "structnk_1_1wavelet_1_1_wenergy_result" ],
        [ "WFiltersResult", "structnk_1_1wavelet_1_1_w_filters_result.html", null ]
      ] ],
      [ "ASTNode", "structnk_1_1_a_s_t_node.html", null ],
      [ "AxesState", "structnk_1_1_axes_state.html", null ],
      [ "BreakpointManager", "classnk_1_1_breakpoint_manager.html", "classnk_1_1_breakpoint_manager" ],
      [ "BreakSignal", "structnk_1_1_break_signal.html", null ],
      [ "BuiltinClass", "structnk_1_1_builtin_class.html", null ],
      [ "BuiltinLibrary", "classnk_1_1_builtin_library.html", null ],
      [ "BytecodeChunk", "structnk_1_1_bytecode_chunk.html", null ],
      [ "CachingMemoryResource", "classnk_1_1_caching_memory_resource.html", null ],
      [ "CallbackBuiltin", "structnk_1_1_callback_builtin.html", null ],
      [ "CallbackFS", "classnk_1_1_callback_f_s.html", null ],
      [ "CallContext", "structnk_1_1_call_context.html", null ],
      [ "ChunkOverflowError", "structnk_1_1_chunk_overflow_error.html", null ],
      [ "Compiler", "classnk_1_1_compiler.html", null ],
      [ "CompilerLimitError", "structnk_1_1_compiler_limit_error.html", null ],
      [ "ContinueSignal", "structnk_1_1_continue_signal.html", null ],
      [ "DataBuffer", "classnk_1_1_data_buffer.html", "classnk_1_1_data_buffer" ],
      [ "DatasetInfo", "structnk_1_1_dataset_info.html", null ],
      [ "DebugContext", "structnk_1_1_debug_context.html", null ],
      [ "DebugController", "classnk_1_1_debug_controller.html", "classnk_1_1_debug_controller" ],
      [ "DebugFacade", "classnk_1_1_debug_facade.html", null ],
      [ "DebugObserver", "classnk_1_1_debug_observer.html", null ],
      [ "DebugSession", "classnk_1_1_debug_session.html", "classnk_1_1_debug_session" ],
      [ "DebugStopException", "classnk_1_1_debug_stop_exception.html", null ],
      [ "DebugWorkspace", "classnk_1_1_debug_workspace.html", null ],
      [ "DecimatedSeries", "structnk_1_1_decimated_series.html", null ],
      [ "DependencyGraph", "classnk_1_1_dependency_graph.html", "classnk_1_1_dependency_graph" ],
      [ "Dims", "structnk_1_1_dims.html", null ],
      [ "DimsArg", "structnk_1_1_dims_arg.html", null ],
      [ "DirEntry", "structnk_1_1_dir_entry.html", null ],
      [ "ElemRegion", "structnk_1_1_elem_region.html", null ],
      [ "Engine", "classnk_1_1_engine.html", "classnk_1_1_engine" ],
      [ "Environment", "classnk_1_1_environment.html", null ],
      [ "Error", "classnk_1_1_error.html", null ],
      [ "FigureManager", "classnk_1_1_figure_manager.html", "classnk_1_1_figure_manager" ],
      [ "FigureState", "structnk_1_1_figure_state.html", "structnk_1_1_figure_state" ],
      [ "FileStat", "structnk_1_1_file_stat.html", null ],
      [ "FsContext", "classnk_1_1_fs_context.html", "classnk_1_1_fs_context" ],
      [ "function_ref", "classnk_1_1function__ref.html", null ],
      [ "function_ref&lt; R(Args...)&gt;", "classnk_1_1function__ref_3_01_r_07_args_8_8_8_08_4.html", "classnk_1_1function__ref_3_01_r_07_args_8_8_8_08_4" ],
      [ "FusionRule", "structnk_1_1_fusion_rule.html", null ],
      [ "GraphicsContext", "structnk_1_1_graphics_context.html", null ],
      [ "GraphicsHandlePayload", "structnk_1_1_graphics_handle_payload.html", null ],
      [ "HeapObject", "structnk_1_1_heap_object.html", null ],
      [ "Import", "structnk_1_1_import.html", null ],
      [ "Instruction", "structnk_1_1_instruction.html", null ],
      [ "Lexer", "classnk_1_1_lexer.html", null ],
      [ "LoopContinuation", "structnk_1_1_loop_continuation.html", null ],
      [ "MethodMeta", "structnk_1_1_method_meta.html", null ],
      [ "NativeFS", "classnk_1_1_native_f_s.html", null ],
      [ "NativePayload", "structnk_1_1_native_payload.html", null ],
      [ "ObjectState", "structnk_1_1_object_state.html", null ],
      [ "Parser", "classnk_1_1_parser.html", null ],
      [ "PlayControl", "structnk_1_1_play_control.html", null ],
      [ "PlayManifest", "structnk_1_1_play_manifest.html", null ],
      [ "PlotEntry", "structnk_1_1_plot_entry.html", null ],
      [ "PropMeta", "structnk_1_1_prop_meta.html", null ],
      [ "ReactiveSession", "classnk_1_1_reactive_session.html", "classnk_1_1_reactive_session" ],
      [ "RegisterExhaustionError", "structnk_1_1_register_exhaustion_error.html", null ],
      [ "ReturnSignal", "structnk_1_1_return_signal.html", null ],
      [ "RuntimeLibrary", "classnk_1_1_runtime_library.html", null ],
      [ "ScratchArena", "classnk_1_1_scratch_arena.html", null ],
      [ "ScratchVec", "classnk_1_1_scratch_vec.html", null ],
      [ "SourceLoc", "structnk_1_1_source_loc.html", null ],
      [ "Span", "classnk_1_1_span.html", null ],
      [ "StackFrame", "structnk_1_1_stack_frame.html", "structnk_1_1_stack_frame" ],
      [ "StackGuard", "classnk_1_1_stack_guard.html", null ],
      [ "StandardEngine", "structnk_1_1_standard_engine.html", null ],
      [ "StandardLibrary", "classnk_1_1_standard_library.html", null ],
      [ "StatementFacts", "structnk_1_1_statement_facts.html", null ],
      [ "Token", "structnk_1_1_token.html", null ],
      [ "TreeWalker", "classnk_1_1_tree_walker.html", "classnk_1_1_tree_walker" ],
      [ "UserFunction", "structnk_1_1_user_function.html", null ],
      [ "Value", "classnk_1_1_value.html", "classnk_1_1_value" ],
      [ "ValueStats", "structnk_1_1_value_stats.html", null ],
      [ "VarRegions", "structnk_1_1_var_regions.html", "structnk_1_1_var_regions" ],
      [ "VirtualFS", "classnk_1_1_virtual_f_s.html", null ],
      [ "VM", "classnk_1_1_v_m.html", "classnk_1_1_v_m" ],
      [ "VmContinuation", "structnk_1_1_vm_continuation.html", null ]
    ] ]
];