var hierarchy =
[
    [ "nk::TreeWalker::ActiveFrame", "structnk_1_1_tree_walker_1_1_active_frame.html", null ],
    [ "nk::image::AdaptHistEqOptions", "structnk_1_1image_1_1_adapt_hist_eq_options.html", null ],
    [ "nk::FigureState::Annotation", "structnk_1_1_figure_state_1_1_annotation.html", null ],
    [ "nk::ASTNode", "structnk_1_1_a_s_t_node.html", null ],
    [ "nk::audio::AudioData", "structnk_1_1audio_1_1_audio_data.html", null ],
    [ "nk::audio::AudioInfo", "structnk_1_1audio_1_1_audio_info.html", null ],
    [ "nk::FigureManager::AxesCheckpoint", "structnk_1_1_figure_manager_1_1_axes_checkpoint.html", null ],
    [ "nk::AxesState", "structnk_1_1_axes_state.html", null ],
    [ "nk::figrender::AxisRange", "structnk_1_1figrender_1_1_axis_range.html", null ],
    [ "nk::linalg::BalanceResult", "structnk_1_1linalg_1_1_balance_result.html", null ],
    [ "nk::control::BodeResult", "structnk_1_1control_1_1_bode_result.html", null ],
    [ "nk::BreakpointManager::Breakpoint", "structnk_1_1_breakpoint_manager_1_1_breakpoint.html", null ],
    [ "nk::BreakpointManager", "classnk_1_1_breakpoint_manager.html", null ],
    [ "nk::BreakSignal", "structnk_1_1_break_signal.html", null ],
    [ "nk::BuiltinClass", "structnk_1_1_builtin_class.html", null ],
    [ "nk::BuiltinLibrary", "classnk_1_1_builtin_library.html", null ],
    [ "nk::BytecodeChunk", "structnk_1_1_bytecode_chunk.html", null ],
    [ "nk::CallbackBuiltin", "structnk_1_1_callback_builtin.html", null ],
    [ "nk::CallContext", "structnk_1_1_call_context.html", null ],
    [ "nk::stats::CanoncorrResult", "structnk_1_1stats_1_1_canoncorr_result.html", null ],
    [ "nk::builtin::CartPair", "structnk_1_1builtin_1_1_cart_pair.html", null ],
    [ "nk::builtin::CartTriple", "structnk_1_1builtin_1_1_cart_triple.html", null ],
    [ "nk::figrender::Cmd", "structnk_1_1figrender_1_1_cmd.html", null ],
    [ "nk::Compiler", "classnk_1_1_compiler.html", null ],
    [ "nk::ContinueSignal", "structnk_1_1_continue_signal.html", null ],
    [ "nk::control::CovarResult", "structnk_1_1control_1_1_covar_result.html", null ],
    [ "nk::signal::CusumResult", "structnk_1_1signal_1_1_cusum_result.html", null ],
    [ "nk::comm::CyclgenResult", "structnk_1_1comm_1_1_cyclgen_result.html", null ],
    [ "nk::builtin::CylTriple", "structnk_1_1builtin_1_1_cyl_triple.html", null ],
    [ "nk::control::DampResult", "structnk_1_1control_1_1_damp_result.html", null ],
    [ "nk::DataBuffer", "classnk_1_1_data_buffer.html", null ],
    [ "nk::DatasetInfo", "structnk_1_1_dataset_info.html", null ],
    [ "nk::wavelet::DdencmpResult", "structnk_1_1wavelet_1_1_ddencmp_result.html", null ],
    [ "nk::DebugContext", "structnk_1_1_debug_context.html", null ],
    [ "nk::DebugController", "classnk_1_1_debug_controller.html", null ],
    [ "nk::DebugFacade", "classnk_1_1_debug_facade.html", null ],
    [ "nk::DebugObserver", "classnk_1_1_debug_observer.html", null ],
    [ "nk::DebugSession", "classnk_1_1_debug_session.html", null ],
    [ "nk::DebugWorkspace", "classnk_1_1_debug_workspace.html", null ],
    [ "nk::DecimatedSeries", "structnk_1_1_decimated_series.html", null ],
    [ "nk::comm::DecodeResult", "structnk_1_1comm_1_1_decode_result.html", null ],
    [ "nk::image::DeconvregResult", "structnk_1_1image_1_1_deconvreg_result.html", null ],
    [ "nk::DependencyGraph", "classnk_1_1_dependency_graph.html", null ],
    [ "nk::Dims", "structnk_1_1_dims.html", null ],
    [ "nk::DimsArg", "structnk_1_1_dims_arg.html", null ],
    [ "nk::ops::DimsArg", "structnk_1_1ops_1_1_dims_arg.html", null ],
    [ "nk::DirEntry", "structnk_1_1_dir_entry.html", null ],
    [ "nk::comm::DpcmOptResult", "structnk_1_1comm_1_1_dpcm_opt_result.html", null ],
    [ "nk::wavelet::Dwt2Result", "structnk_1_1wavelet_1_1_dwt2_result.html", null ],
    [ "nk::ElemRegion", "structnk_1_1_elem_region.html", null ],
    [ "nk::builtin::EllipJ", "structnk_1_1builtin_1_1_ellip_j.html", null ],
    [ "nk::builtin::EllipKE", "structnk_1_1builtin_1_1_ellip_k_e.html", null ],
    [ "nk::comm::EncodeResult", "structnk_1_1comm_1_1_encode_result.html", null ],
    [ "nk::Engine", "classnk_1_1_engine.html", [
      [ "nk::StandardEngine", "structnk_1_1_standard_engine.html", null ]
    ] ],
    [ "nk::Environment", "classnk_1_1_environment.html", null ],
    [ "nk::Engine::EvalResult", "structnk_1_1_engine_1_1_eval_result.html", null ],
    [ "std::exception", null, [
      [ "std::runtime_error", null, [
        [ "nk::CompilerLimitError", "structnk_1_1_compiler_limit_error.html", [
          [ "nk::ChunkOverflowError", "structnk_1_1_chunk_overflow_error.html", null ],
          [ "nk::RegisterExhaustionError", "structnk_1_1_register_exhaustion_error.html", null ]
        ] ],
        [ "nk::DebugStopException", "classnk_1_1_debug_stop_exception.html", null ],
        [ "nk::Error", "classnk_1_1_error.html", null ]
      ] ]
    ] ],
    [ "nk::FigureManager::FigureCheckpoint", "structnk_1_1_figure_manager_1_1_figure_checkpoint.html", null ],
    [ "nk::FigureManager", "classnk_1_1_figure_manager.html", null ],
    [ "nk::FigureState", "structnk_1_1_figure_state.html", null ],
    [ "nk::FileStat", "structnk_1_1_file_stat.html", null ],
    [ "nk::wavelet::FilterBank", "structnk_1_1wavelet_1_1_filter_bank.html", null ],
    [ "nk::builtin::FindgroupsResult", "structnk_1_1builtin_1_1_findgroups_result.html", null ],
    [ "nk::signal::Fir2Options", "structnk_1_1signal_1_1_fir2_options.html", null ],
    [ "nk::DebugController::FrameGuard", "classnk_1_1_debug_controller_1_1_frame_guard.html", null ],
    [ "nk::VM::FrameView", "structnk_1_1_v_m_1_1_frame_view.html", null ],
    [ "nk::FsContext", "classnk_1_1_fs_context.html", null ],
    [ "nk::io::FsContext", "classnk_1_1io_1_1_fs_context.html", null ],
    [ "nk::function_ref&lt; Sig &gt;", "classnk_1_1function__ref.html", null ],
    [ "nk::function_ref&lt; R(Args...)&gt;", "classnk_1_1function__ref_3_01_r_07_args_8_8_8_08_4.html", null ],
    [ "nk::FusionRule", "structnk_1_1_fusion_rule.html", null ],
    [ "nk::stats::GlmfitResult", "structnk_1_1stats_1_1_glmfit_result.html", null ],
    [ "nk::GraphicsContext", "structnk_1_1_graphics_context.html", null ],
    [ "nk::builtin::GroupcountsResult", "structnk_1_1builtin_1_1_groupcounts_result.html", null ],
    [ "nk::builtin::GroupsummaryResult", "structnk_1_1builtin_1_1_groupsummary_result.html", null ],
    [ "nk::stats::Grp2idxResult", "structnk_1_1stats_1_1_grp2idx_result.html", null ],
    [ "nk::wavelet::HaartResult", "structnk_1_1wavelet_1_1_haart_result.html", null ],
    [ "nk::comm::HammgenResult", "structnk_1_1comm_1_1_hammgen_result.html", null ],
    [ "nk::FigureManager::HandleRecord", "structnk_1_1_figure_manager_1_1_handle_record.html", null ],
    [ "nk::HeapObject", "structnk_1_1_heap_object.html", null ],
    [ "nk::bundle::HelpCatalog", "classnk_1_1bundle_1_1_help_catalog.html", null ],
    [ "nk::bundle::HelpCategory", "structnk_1_1bundle_1_1_help_category.html", null ],
    [ "nk::bundle::HelpEntry", "structnk_1_1bundle_1_1_help_entry.html", null ],
    [ "nk::bundle::HelpLibrary", "classnk_1_1bundle_1_1_help_library.html", null ],
    [ "nk::bundle::HelpSection", "structnk_1_1bundle_1_1_help_section.html", null ],
    [ "nk::builtin::HistBinSpec", "structnk_1_1builtin_1_1_hist_bin_spec.html", null ],
    [ "nk::Import", "structnk_1_1_import.html", null ],
    [ "nk::builtin::InpolygonResult", "structnk_1_1builtin_1_1_inpolygon_result.html", null ],
    [ "nk::Instruction", "structnk_1_1_instruction.html", null ],
    [ "nk::stats::LassoResult", "structnk_1_1stats_1_1_lasso_result.html", null ],
    [ "nk::runtime::LastWarn", "structnk_1_1runtime_1_1_last_warn.html", null ],
    [ "nk::Lexer", "classnk_1_1_lexer.html", null ],
    [ "nk::control::MarginResult", "structnk_1_1control_1_1_margin_result.html", null ],
    [ "nk::builtin::MatchpairsResult", "structnk_1_1builtin_1_1_matchpairs_result.html", null ],
    [ "std::pmr::memory_resource", null, [
      [ "nk::CachingMemoryResource", "classnk_1_1_caching_memory_resource.html", null ]
    ] ],
    [ "nk::MethodMeta", "structnk_1_1_method_meta.html", null ],
    [ "std::pmr::monotonic_buffer_resource", null, [
      [ "nk::ScratchArena", "classnk_1_1_scratch_arena.html", null ]
    ] ],
    [ "nk::figrender::NamedPaletteHex", "structnk_1_1figrender_1_1_named_palette_hex.html", null ],
    [ "nk::ops::NanSumCount", "structnk_1_1ops_1_1_nan_sum_count.html", null ],
    [ "nk::NativePayload", "structnk_1_1_native_payload.html", [
      [ "nk::GraphicsHandlePayload", "structnk_1_1_graphics_handle_payload.html", null ]
    ] ],
    [ "nk::stats::NlinfitResult", "structnk_1_1stats_1_1_nlinfit_result.html", null ],
    [ "nk::linalg::NnlsResult", "structnk_1_1linalg_1_1_nnls_result.html", null ],
    [ "nk::stats::NormalizeResult", "structnk_1_1stats_1_1_normalize_result.html", null ],
    [ "nk::control::NyquistResult", "structnk_1_1control_1_1_nyquist_result.html", null ],
    [ "nk::ObjectState", "structnk_1_1_object_state.html", null ],
    [ "nk::FsContext::OpenFile", "structnk_1_1_fs_context_1_1_open_file.html", null ],
    [ "nk::io::FsContext::OpenFile", "structnk_1_1io_1_1_fs_context_1_1_open_file.html", null ],
    [ "nk::wavelet::OrthfiltResult", "structnk_1_1wavelet_1_1_orthfilt_result.html", null ],
    [ "nk::builtin::PadeCoef", "structnk_1_1builtin_1_1_pade_coef.html", null ],
    [ "nk::Parser", "classnk_1_1_parser.html", null ],
    [ "nk::VM::PausedState", "structnk_1_1_v_m_1_1_paused_state.html", null ],
    [ "nk::PlayControl", "structnk_1_1_play_control.html", null ],
    [ "nk::PlayManifest", "structnk_1_1_play_manifest.html", null ],
    [ "nk::PlotEntry", "structnk_1_1_plot_entry.html", null ],
    [ "nk::builtin::PolarPair", "structnk_1_1builtin_1_1_polar_pair.html", null ],
    [ "nk::builtin::PolyDiv", "structnk_1_1builtin_1_1_poly_div.html", null ],
    [ "nk::builtin::PolyxpolyResult", "structnk_1_1builtin_1_1_polyxpoly_result.html", null ],
    [ "nk::PropMeta", "structnk_1_1_prop_meta.html", null ],
    [ "nk::comm::QuantizResult", "structnk_1_1comm_1_1_quantiz_result.html", null ],
    [ "nk::figrender::Raster", "classnk_1_1figrender_1_1_raster.html", null ],
    [ "nk::ReactiveSession", "classnk_1_1_reactive_session.html", null ],
    [ "nk::figrender::Rect", "structnk_1_1figrender_1_1_rect.html", null ],
    [ "nk::builtin::ResidueResult", "structnk_1_1builtin_1_1_residue_result.html", null ],
    [ "nk::FsContext::ResolvedPath", "structnk_1_1_fs_context_1_1_resolved_path.html", null ],
    [ "nk::io::FsContext::ResolvedPath", "structnk_1_1io_1_1_fs_context_1_1_resolved_path.html", null ],
    [ "nk::ReturnSignal", "structnk_1_1_return_signal.html", null ],
    [ "nk::figrender::Rgb", "structnk_1_1figrender_1_1_rgb.html", null ],
    [ "nk::control::RiccatiResult", "structnk_1_1control_1_1_riccati_result.html", null ],
    [ "nk::builtin::RngContext", "classnk_1_1builtin_1_1_rng_context.html", null ],
    [ "nk::ops::RngContext", "classnk_1_1ops_1_1_rng_context.html", null ],
    [ "nk::stats::RobustcovResult", "structnk_1_1stats_1_1_robustcov_result.html", null ],
    [ "nk::stats::RobustfitResult", "structnk_1_1stats_1_1_robustfit_result.html", null ],
    [ "nk::RuntimeLibrary", "classnk_1_1_runtime_library.html", null ],
    [ "nk::builtin::detail::ScanfOut", "structnk_1_1builtin_1_1detail_1_1_scanf_out.html", null ],
    [ "nk::detail::ScratchStorage", "structnk_1_1detail_1_1_scratch_storage.html", [
      [ "nk::ScratchArena", "classnk_1_1_scratch_arena.html", null ]
    ] ],
    [ "nk::builtin::ShiftDimAuto", "structnk_1_1builtin_1_1_shift_dim_auto.html", null ],
    [ "nk::ops::SizeSpec", "structnk_1_1ops_1_1_size_spec.html", null ],
    [ "nk::DebugSession::Snapshot", "structnk_1_1_debug_session_1_1_snapshot.html", null ],
    [ "nk::SourceLoc", "structnk_1_1_source_loc.html", null ],
    [ "nk::Span&lt; T &gt;", "classnk_1_1_span.html", null ],
    [ "nk::builtin::SphTriple", "structnk_1_1builtin_1_1_sph_triple.html", null ],
    [ "nk::StackFrame", "structnk_1_1_stack_frame.html", null ],
    [ "nk::StackGuard", "classnk_1_1_stack_guard.html", null ],
    [ "nk::StandardLibrary", "classnk_1_1_standard_library.html", null ],
    [ "nk::StatementFacts", "structnk_1_1_statement_facts.html", null ],
    [ "nk::control::StateSpace", "structnk_1_1control_1_1_state_space.html", null ],
    [ "nk::figrender::StyleParts", "structnk_1_1figrender_1_1_style_parts.html", null ],
    [ "nk::builtin::Surface3", "structnk_1_1builtin_1_1_surface3.html", null ],
    [ "nk::figrender::TextExtras", "structnk_1_1figrender_1_1_text_extras.html", null ],
    [ "nk::control::Tf2ZpResult", "structnk_1_1control_1_1_tf2_zp_result.html", null ],
    [ "nk::detail::ThreadPool", "classnk_1_1detail_1_1_thread_pool.html", null ],
    [ "nk::Token", "structnk_1_1_token.html", null ],
    [ "nk::TreeWalker", "classnk_1_1_tree_walker.html", null ],
    [ "nk::UserFunction", "structnk_1_1_user_function.html", null ],
    [ "nk::Value", "classnk_1_1_value.html", null ],
    [ "nk::detail::value_type_for&lt; T &gt;", "structnk_1_1detail_1_1value__type__for.html", null ],
    [ "nk::detail::value_type_for&lt; double &gt;", "structnk_1_1detail_1_1value__type__for_3_01double_01_4.html", null ],
    [ "nk::detail::value_type_for&lt; float &gt;", "structnk_1_1detail_1_1value__type__for_3_01float_01_4.html", null ],
    [ "nk::detail::value_type_for&lt; std::complex&lt; double &gt; &gt;", "structnk_1_1detail_1_1value__type__for_3_01std_1_1complex_3_01double_01_4_01_4.html", null ],
    [ "nk::detail::value_type_for&lt; std::int16_t &gt;", "structnk_1_1detail_1_1value__type__for_3_01std_1_1int16__t_01_4.html", null ],
    [ "nk::detail::value_type_for&lt; std::int32_t &gt;", "structnk_1_1detail_1_1value__type__for_3_01std_1_1int32__t_01_4.html", null ],
    [ "nk::detail::value_type_for&lt; std::int64_t &gt;", "structnk_1_1detail_1_1value__type__for_3_01std_1_1int64__t_01_4.html", null ],
    [ "nk::detail::value_type_for&lt; std::int8_t &gt;", "structnk_1_1detail_1_1value__type__for_3_01std_1_1int8__t_01_4.html", null ],
    [ "nk::detail::value_type_for&lt; std::uint16_t &gt;", "structnk_1_1detail_1_1value__type__for_3_01std_1_1uint16__t_01_4.html", null ],
    [ "nk::detail::value_type_for&lt; std::uint32_t &gt;", "structnk_1_1detail_1_1value__type__for_3_01std_1_1uint32__t_01_4.html", null ],
    [ "nk::detail::value_type_for&lt; std::uint64_t &gt;", "structnk_1_1detail_1_1value__type__for_3_01std_1_1uint64__t_01_4.html", null ],
    [ "nk::detail::value_type_for&lt; std::uint8_t &gt;", "structnk_1_1detail_1_1value__type__for_3_01std_1_1uint8__t_01_4.html", null ],
    [ "nk::ValueStats", "structnk_1_1_value_stats.html", null ],
    [ "nk::StackFrame::VarEntry", "structnk_1_1_stack_frame_1_1_var_entry.html", null ],
    [ "nk::DebugSession::Variable", "structnk_1_1_debug_session_1_1_variable.html", null ],
    [ "nk::VarRegions", "structnk_1_1_var_regions.html", null ],
    [ "std::pmr::vector", null, [
      [ "nk::ScratchVec< T >", "classnk_1_1_scratch_vec.html", null ]
    ] ],
    [ "nk::DataBuffer::ViewTag", "structnk_1_1_data_buffer_1_1_view_tag.html", null ],
    [ "nk::VirtualFS", "classnk_1_1_virtual_f_s.html", [
      [ "nk::CallbackFS", "classnk_1_1_callback_f_s.html", null ],
      [ "nk::NativeFS", "classnk_1_1_native_f_s.html", null ]
    ] ],
    [ "nk::VM", "classnk_1_1_v_m.html", null ],
    [ "nk::VmContinuation", "structnk_1_1_vm_continuation.html", [
      [ "nk::LoopContinuation", "structnk_1_1_loop_continuation.html", null ]
    ] ],
    [ "nk::DebugSession::WatchResult", "structnk_1_1_debug_session_1_1_watch_result.html", null ],
    [ "nk::wavelet::Wavedec2Result", "structnk_1_1wavelet_1_1_wavedec2_result.html", null ],
    [ "nk::wavelet::WenergyResult", "structnk_1_1wavelet_1_1_wenergy_result.html", null ],
    [ "nk::wavelet::WFiltersResult", "structnk_1_1wavelet_1_1_w_filters_result.html", null ]
];